#!/usr/bin/env bash
# Compile a hashed requirements.lock for reproducible release builds.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if command -v uv >/dev/null 2>&1; then
  echo "Compiling requirements.lock with uv (hashes)…"
  uv pip compile requirements.txt --generate-hashes -o requirements.lock
elif python3 -m piptools --help >/dev/null 2>&1; then
  echo "Compiling requirements.lock with pip-tools…"
  python3 -m piptools compile --generate-hashes -o requirements.lock requirements.txt
else
  echo "uv / pip-tools not found — writing freeze lock without hashes from .venv" >&2
  if [ ! -x "$ROOT/.venv/bin/pip" ]; then
    echo "Need .venv or uv to produce a lock file." >&2
    exit 1
  fi
  {
    echo "# Autogenerated freeze (no hashes). Prefer: ./scripts/lock_requirements.sh with uv"
    "$ROOT/.venv/bin/pip" freeze
  } > requirements.lock
fi

echo "Wrote $ROOT/requirements.lock"
